Going through the numpy....

Concept of arrays

In [4]:
import numpy as np

In [ ]:


arr1 = np.array([[1,2,3,4,5],[7,8,9,10,11]])
arr2 = np.array(["a", "b", "c"])
print(arr1)
print(arr2)
print(arr1.shape)
print(arr2.shape)

[[ 1  2  3  4  5]
 [ 7  8  9 10 11]]
['a' 'b' 'c']
(2, 5)
(3,)


In [9]:
#arrange method

a = np.arange(1,13,2)
b = a.reshape(6,1)
print(b)

[[ 1]
 [ 3]
 [ 5]
 [ 7]
 [ 9]
 [11]]


In [14]:
#ones function 

np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [17]:
#identity matrix

np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Numpy Vectorized Operations

In [5]:
arr1 = np.array([10,5,6,11,2])
arr2 = np.array([11,9,4,6,2])
#element wise addition
print("Addition: ",arr1 + arr2)
#element wise substraction
print("Substraction: ",arr1 - arr2)
#element wise multipication
print("Multiplication: ", arr1 * arr2)
#element wise division
print("Division: ",arr1 / arr2)

Addition:  [21 14 10 17  4]
Substraction:  [-1 -4  2  5  0]
Multiplication:  [110  45  24  66   4]
Division:  [0.90909091 0.55555556 1.5        1.83333333 1.        ]


Universal Function

In [7]:
arr = np.array([4,8,3,8,45,0])
arr2 = np.array([4,8,3,8,45])

#square root
print("Square root: ",np.sqrt(arr))
#exponential
print("Exponential value: ",np.exp(arr))
#sin
print("Sin Value: ", np.sin(arr))

#cos
print("Cos value: ",np.cos(arr))

#natural log
print("Natural log: ",np.log(arr2))


Square root:  [2.         2.82842712 1.73205081 2.82842712 6.70820393 0.        ]
Exponential value:  [5.45981500e+01 2.98095799e+03 2.00855369e+01 2.98095799e+03
 3.49342711e+19 1.00000000e+00]
Sin Value:  [-0.7568025   0.98935825  0.14112001  0.98935825  0.85090352  0.        ]
Cos value:  [-0.65364362 -0.14550003 -0.9899925  -0.14550003  0.52532199  1.        ]
Natural log:  [1.38629436 2.07944154 1.09861229 2.07944154 3.80666249]


Array slicing and indexing

In [ ]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Given Array is:\n",arr)

print("First row second column element is:", arr[0][1])

#picking particular part of row and column

print("Elements after 7 in second row and elements after 11 in thrid row:\n",arr[1:,2:])

print("\n", arr[0:2,2:])

print("\n",arr[1:3,1:3] )

#Gives element of 1st and third column of first and second row
print("\n element of 1st and third column of first and second row:\n", arr[[0,1],:][:,[0,2]])

Given Array is:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
First row second column element is: 2
Elements after 7 in second row and elements after 11 in thrid row:
 [[ 7  8]
 [11 12]]

 [[3 4]
 [7 8]]

 [[ 6  7]
 [10 11]]

 [[1 3 2]
 [5 7 6]]


Modify the array elements

In [42]:
arr[1,3] = 5
print(arr)

arr[0:3,0:3] = 1
print("Making every element of 1st to 2nd row and 1st to 3rd column to 1:\n",arr)


[[ 1  2  3  4]
 [ 5  6  7  5]
 [ 9 10 11 12]]
Making every element of 1st to 2nd row and 1st to 3rd column to 1:
 [[ 1  1  1  4]
 [ 1  1  1  5]
 [ 1  1  1 12]]


Concept of Normalization:

Standard normal distribution concept:

Formula (value - mean) / SD


In [43]:
arr = np.array([2,5,7,10,7])

mean_value = np.mean(arr)
SD_value = np.std(arr)

normalized_value = (arr - mean_value)  / SD_value

print("Normalized value:\n",normalized_value)

Normalized value:
 [-1.59200589 -0.45485883  0.30323922  1.44038628  0.30323922]


Calculation mean, median, standard deviation and variance

In [44]:
arr = np.array([2,5,8,1,3])

mean = np.mean(arr)
print("Mean is:\n", mean)

median = np.median(arr)
print("Median is:\n", median)

sd = np.std(arr)
print("SD is:\n", sd)

var = np.var(arr)
print("Variance is:\n", var)

Mean is:
 3.8
Median is:
 3.0
SD is:
 2.4819347291981715
Variance is:
 6.16


Logical operations 

In [49]:
data = np.array([2,4,7,9,10])

print(data > 5)

print(data[data > 5])

print(data[data != 2])

print(data[(data > 2) & (data < 9)])

[False False  True  True  True]
[ 7  9 10]
[ 4  7  9 10]
[4 7]
