Going through the numpy....

Concept of arrays

In [5]:
import numpy as np

arr1 = np.array([[1,2,3,4,5],[7,8,9,10,11]])
arr2 = np.array(["a", "b", "c"])
print(arr1)
print(arr2)
print(arr1.shape)
print(arr2.shape)

[[ 1  2  3  4  5]
 [ 7  8  9 10 11]]
['a' 'b' 'c']
(2, 5)
(3,)


In [9]:
#arrange method

a = np.arange(1,13,2)
b = a.reshape(6,1)
print(b)

[[ 1]
 [ 3]
 [ 5]
 [ 7]
 [ 9]
 [11]]


In [14]:
#ones function 

np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [17]:
#identity matrix

np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])